Sprint 8 solution time and duration
lazarx77/java-kanban pull request #6
Opened 2024-05-24 08:59 UTC by lazarx77

Доработка функционала в соответствии с ТЗ.

2024-05-25 14:50 UTC, kriwsha requested changes

2024-05-25 14:50 UTC, kriwsha commented on src/model/Epic.java
> +    //private long duration;
Неиспользуемые строки кода следует удалять

2024-05-25 14:50 UTC, kriwsha commented on src/service/FileBackedTaskManager.java
> +                result = result + null + ",";
Добавлять null не нужно - это все равно ничего, поэтому следует упустить. Ниже тоже следует убрать null

2024-05-25 14:50 UTC, kriwsha commented on src/service/InMemoryTaskManager.java
> +                    throw new TimeCrossException("");
Не нужно оставлять пустое сообщение об ошибке

2024-05-25 14:50 UTC, kriwsha commented on src/service/InMemoryTaskManager.java
> +            throw new TimeCrossException("Задача не добавлена: пересечение задач по времени.");
Получается, что вы ловите это исключение и снова пробрасываете такое же. Я бы рекомендовал поправить - лучше сразу выкидывать нужное исключение. Ниже тоже рекомендовал бы исправить

2024-05-25 14:50 UTC, kriwsha commented on src/service/TimeCrossException.java
> +public class TimeCrossException extends RuntimeException {
Не забывайте комментировать свой код. Эта привычка в будущем вам сослужит хорошую службу

2024-05-26 05:36 UTC, lazarx77 commented on src/model/Epic.java
> +    //private long duration;
Пробежался по всему коду, неиспользуемые строки кода удалил.

2024-05-26 05:36 UTC, lazarx77 commented on src/service/FileBackedTaskManager.java
> +                result = result + null + ",";
Убрал добавление null из кода, поправил логику считывания задачи из строки.

2024-05-26 05:37 UTC, lazarx77 commented on src/service/InMemoryTaskManager.java
> +                    throw new TimeCrossException("");
исправил

2024-05-26 05:37 UTC, lazarx77 commented on src/service/InMemoryTaskManager.java
> +            throw new TimeCrossException("Задача не добавлена: пересечение задач по времени.");
исправил, теперь исключение о пересечении задач по времени выбрасывается сразу с нужным сообщением

2024-05-26 05:37 UTC, lazarx77 commented on src/service/TimeCrossException.java
> +public class TimeCrossException extends RuntimeException {
добавил больше комментариев к коду

2024-05-26 18:08 UTC, kriwsha approved these changes

2024-05-27 05:11 UTC, merged