Peer review
lazarx77/java-kanban pull request #7
Opened 2024-05-24 15:24 UTC by lazarx77

Ветка для отработки навыков peer-review

2024-05-27 19:09 UTC, akuniutka requested changes
Большая работа! Я оставил комментарии к некоторым местам в основном коде и предлагаю проговорить сначала эти моменты. А к тестам, если хочешь их тоже обсудить, перейти потом.

2024-05-27 19:09 UTC, akuniutka commented on savedTasks.txt
Если этот файл больше не планируем использовать, предлагаю удалить его из репозитория.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
> +        return startTime.plus(getDuration());
Предлагаю предусмотреть обработку случая, когда в `startTime` находится `null` (например, сразу после создания `Task`, когда поле `startTime` ещё не проинициализировано через соответствующий сеттер).

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
> +    LocalDateTime startTime; //может быть равным null
Предлагаю указать идентификаторы доступа к полям `duration` и `startTime`.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
> +    public static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy - HH:mm");
Предлагаю вынести `formatter` в отдельный утилитный класс. Сейчас, на мой взгляд, при проектировании новых классов будет неочевидно, что нужный `formatter` следует искать в классе `Task`.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
>              result = result + ", extraInfo=null";
Возможно, `description` вместо `extraInfo`?

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
> +            this.duration = duration.toMinutes();
Обрати внимание: `Duration` может содержать отрицательные значения.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Task.java
Насколько нужен параметр `id` в методе `getTaskName()`?

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
>      private Integer id;
Это поле дублирует поле `id`, которое класс `Epic` наследует от класса `Task`.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
>      public List<Integer> addSubtasksIds(int id) {
Поскольку в методе мы за один раз добавляем только один новый `id`, предлагаю назвать его `addSubtaskId` либо `addToSubtaskIds`. Аналогично для метода `removeSubtasksIds()`.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
> +    }
Если метод `getEpicEndTime()` не планируем использовать, предлагаю его удалить.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
> +    }
Так как метод `getEndTime()` (см. выше) всё равно "перепрошивает" значение поля `endTime`, а другого геттера для `endTime` нет, предлагаю метод `setEndTime(LocalDateTime starTime)` просто удалить.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
>              result = result + ", extraInfo=null";
Возможно, `description` вместо `extraInfo`?

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
> +    }
Метод возвращает то же значение, что и метод родительского класса. Соответственно, можно его не переопределять и просто воспользоваться унаследованным вариантом.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Epic.java
> +    private LocalDateTime endTime;
Значение этого поля по факту нигде не используется, поэтому предлагаю поле удалить.

2024-05-27 19:09 UTC, akuniutka commented on src/model/Subtask.java
>              result = result + ", extraInfo=null";
Возможно, `description` вместо `extraInfo`?

2024-05-27 19:09 UTC, akuniutka commented on src/service/TimeCrossException.java
См. выше про отдельный пакет для классов исключений.

2024-05-27 19:09 UTC, akuniutka commented on testFile.txt
Если этот файл больше не планируем использовать, предлагаю удалить его из репозитория.

2024-05-27 19:09 UTC, akuniutka commented on testFile.csv
Предлагаю для тестовых данных создать отдельную папку `resources` рядом с уже существующими `src` и `test`, чтобы оставить в корневой папке проекта только те файлы, которые относятся к проекту в целом. А для временных файлов, которые нужны исключительно во время работы тестов, предлагаю использовать метод [`createTempFile`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Files.html#createTempFile(java.lang.String,java.lang.String,java.nio.file.attribute.FileAttribute...)) класса `Files`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/ManagerSaveException.java
Предлагаю для классов исключений создать отдельный пакет: их уже два, с классами менеджеров они связаны не сильнее, чем классы для задач, а у последних свой отдельный пакет.

2024-05-27 19:09 UTC, akuniutka commented on src/service/Managers.java
Сейчас если в рамках одной программы запустить два менеджера задач (каждый со своим списком), они будут использовать один и тот же экземпляр `HistoryManager` и перезаписывать историю друг друга. Возможно, будет лучше из метода `getDefaultHistory()` каждый раз возвращать новый экземпляр соответствующего класса.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
>      protected List<Integer> subtasksIds = new ArrayList<>();
Это поле используется только внутри метода `setEpicStart()`. Может перенести его туда?

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));
Предлагаю инициализацию полей `historyManager` и `prioritizedTasks` также осуществлять в конструкторе, чтобы все начальные значения можно было посмотреть в одном месте.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +                    .findFirst().orElse(null);
В данном случае метод `min()` будет работать быстрее связки `sorted().findFirst()`: `O(n)` по сравнению с `O(n log n)`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +    private void setEpicStart(int id) {
Так как метод устанавливает для эпика также значение поля `duration`, предлагаю назвать его `setEpicStartAndDuration`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +                epic.setEndTime(epicEndTime);
См. выше про то, что метод `getEndTime()` класса `Epic` "перепрошивает" данное значение. Также предлагаю рассмотреть случай, когда у эпика две подзадачи: с 09:00 по 10:00 и с 18:00 по 19:00 — по условиям ТЗ метод `getEndTime()` для такого эпика должен вернуть 19:00.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +                .toList();
Вместо `epics.get(id)` можно воспользоваться значением `epic`, полученным строчкой выше.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
>                  !statusList.contains(TaskStatus.IN_PROGRESS)) {
- Проверку на наличие можно ускорить с `O(n)` до `O(1)`, если вместо `List` использовать `HashSet`.
- Похоже, для эпика без подзадач метод получит статус IN_PROGRESS вместо NEW.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
Предлагаю в методе `deleteEpic()` вместо цикла использовать стрим.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
Предлагаю добавить тест с вызовом метода `clearAllSubtasks()`, когда в менеджере есть хотя бы две подзадачи.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
>          }
Предлагаю заменить цикл на стрим.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
Также предлагаю проверить, удаляются ли из `historyManager` и `prioritizedTasks` подзадачи при вызове методе `clearAllEpics()`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +            if (prioritizedTasks.contains(task)) {
Если в новой версии задачи указано новое время, то поиск в `TreeSet` не найдёт предыдущую версию — `TreeSet` в качестве ключа использует значение поля `startTime`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +            if (prioritizedTasks.contains(subtask)) {
См. выше про то, что `TreeSet` в качестве ключа использует значение поля `startTime` и что если в новой версии подзадачи значение в этом поле изменилось, поиск по `subtask` не сможет найти предыдущую версию.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +        id++;
Имеет ли смысл увеличивать здесь счётчик?

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +        tasks.put(id, subtask);
Возможно, опечатка?

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +            setEpicStart(id);
Обрати внимание: методы `setEpicStatus()` и `setEpicStart()` работают с той версией эпика, которая в настоящий момент лежит в `epics`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
Предлагаю в методе `updateEpic(Epic epic)` вместо цикла использовать стрим.

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +        return new ArrayList<>(tasks.values());
Отличное использование коллекций Java!

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +        return epics.get(id).getSubtasksIds().stream().map(subtasks::get).toList();
Отличный пример использования Stream API!

2024-05-27 19:09 UTC, akuniutka commented on src/service/InMemoryTaskManager.java
> +                .anyMatch(pt -> (task.getStartTime() != null) && (task.getDuration() != null)
Метод `getDuration()` класса `Task` никогда не возвращает `null`, поэтому проверка `task.getDuration() != null` в данном случае не влияет на результат.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
В методе `save` вместо:
- `super.getAllTasks()`
- `super.getAllEpics()`
- `super.getAllSubtasks()`

можно писать сразу:
- `getAllTasks()`
- `getAllEpics()`
- `getAllSubtasks()`

и не оборачивать соответствующие циклы `for each` в `if` — если какая-то коллекция окажется пустой, цикл по ней не запустится.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
Предлагаю также в методе `save` вместо `FileWriter` использовать `Files.write()`, а `List<String>` для него собирать с помощью стримов.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
>          if (task.toString().startsWith("Task")) {
Проверка `task.getType() == TaskType.TASK` будет рабоать быстрее.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +            if (task.getDuration() != null) {
Метод `getDuraion()` класса `Task` никогда не возвращает `null`, поэтому проверку можно не делать.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +            }
Если в строке #229 заменить `TaskType.EPIC` на `task.getType()`, то первые две ветки `if` можно объединить в одну.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +            if (task.getDuration() != null) {
См. выше про то, что метод `getDuration()` класса `Task` никогда не возвращает `null`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    epic.setStartTime(null);
Метод `setStartTime()` игнорирует значения, равные `null`. Эту строчку можно удалить.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    epic.setDuration(null);
Метод `setDuration()` также игнорирует `null`. Эту строчку тоже можно удалить.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    subtask.setStartTime(null);
См. выше про то, что метод `setStartTime()` игнорирует `null`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    subtask.setDuration(null);
См. выше про то, что метод `setDuration()` игнорирует `null`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    task.setStartTime(null);
См. выше про то, что метод `setStartTime()` игнорирует `null`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
> +                    task.setDuration(null);
См. выше про то, что метод `setDuration()` игнорирует `null`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
В методе `loadFromFile`:
- Один из двух `BufferedReader` (`fileReader` и `br`) можно убрать, для работы метода достаточно одного.
- Вместо `ManagerSaveException` предлагаю выбрасывать исключение с другим названием, этот класс может ввести пользователя в заблуждение.
- Можно перед чиклом `while` один раз вызвать метод `readLine()` у экземпляра `BufferedReader`, чтобы в цикле не делать проверку:
```java
if (!line.startsWith("id")) {
```
- Можно вместо `BufferedReader` воспользоваться методом [`readAllLines`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/Files.html#readAllLines(java.nio.file.Path,java.nio.charset.Charset)) класса `Files` и работать с уже готовым `List<String>`.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
>                  return null;
Предлагаю здесь выбрасывать какое-нибудь исключение, чтобы в методе `loadFromFile` не возникало `NullPointerException` при обращении к методу `getId()` этого `null`, — разобраться в причинах такого `NullPointerException` будет сложнее.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
>                              break;
Надо также добавить подзадачу в эпик.

2024-05-27 19:09 UTC, akuniutka commented on src/service/FileBackedTaskManager.java
Предлагаю перенести тестовый пример из метода `main()` в тестовый класс — там с помощью JUnit можно автоматически проверять, что программа выводит корректные данные.

2024-05-27 19:09 UTC, akuniutka commented on src/Main.java
Предлагаю перенести код из метода `main()` в тестовый класс, там можно подключить автоматическую проверку результата.

2024-06-05 08:45 UTC, lazarx77 commented on src/model/Task.java
> +    LocalDateTime startTime; //может быть равным null
поправил

2024-06-11 17:31 UTC, lazarx77 commented on savedTasks.txt
файл убрал

2024-12-17 10:30 UTC, closed without merging