Sprint 9 solution http api
lazarx77/java-kanban pull request #8
Opened 2024-06-09 06:08 UTC by lazarx77

Доработка функционала в соответствии с ТЗ 9 спринта.

2024-06-10 17:22 UTC, kriwsha requested changes

2024-06-10 17:22 UTC, kriwsha commented on src/Main.java
> +//        task2 = taskManager.createNewTask(task2);
закоментированный код следует удалять

2024-06-10 17:22 UTC, kriwsha commented on src/adapters/LocalDateTimeAdapter.java
> +//создаем адаптер для gson-json
я бы рекомендовал уйти от обычных комментариев в сторону документирующих

2024-06-10 17:22 UTC, kriwsha commented on src/servers/HttpTaskServer.java
> +        // httpTaskServer.stop(5); // заготовка для остановки сервера
здесь также следует удалить

2024-06-10 17:22 UTC, kriwsha commented on src/servers/PrioritizedHandler.java
> +public class PrioritizedHandler extends BaseHttpHandler {
не забывайте документировать код. это важно, особенно когда только начинаешь разбираться в проекте

2024-06-10 17:22 UTC, kriwsha commented on src/service/InMemoryTaskManager.java
> +            if (tasks.get(id).getStartTime() != null) {
вот такую вложенность я предпочитаю избегать. для этого можно "перевернуть" блок if-else: if (task... == null) выкинуть исключение, а затем уже можно без блока else. это вкусовщина, но часто код становится более читаемым

2024-06-10 17:22 UTC, kriwsha commented on src/service/InMemoryTaskManager.java
> +                if (prioritizedTasks.contains(task)) {
здесь это особенно заметно, что такая вложенность сложно читается

2024-06-10 17:22 UTC, kriwsha commented on src/servers/BaseHttpHandler.java
> +        if (splitStrings.length >= 3) { // получаем переданный в пути id задачи
на будущее. такие неожиданные цифры в коде называют magic numbers. часто рекомендуют создавать константу, которая описывает эту переменную, а затем использовать эту константу. в этом случае код становится более читаемым

2024-06-10 17:22 UTC, kriwsha commented on src/servers/EpicsHandler.java
> +                sendText(exc, response, 205);
двухсотый код (то есть 200+) означает успешное выполнение. но у вас ошибка, то есть нужно выбрать новый код

2024-06-10 17:49 UTC, lazarx77 commented on src/adapters/LocalDateTimeAdapter.java
> +//создаем адаптер для gson-json
учту на будущее

2024-06-10 18:50 UTC, lazarx77 commented on src/servers/BaseHttpHandler.java
> +        if (splitStrings.length >= 3) { // получаем переданный в пути id задачи
убрал лишнюю инициализацию поля idInt

2024-06-10 18:54 UTC, lazarx77 commented on src/servers/HttpTaskServer.java
> +        // httpTaskServer.stop(5); // заготовка для остановки сервера
исправил

2024-06-10 18:55 UTC, lazarx77 commented on src/servers/PrioritizedHandler.java
> +public class PrioritizedHandler extends BaseHttpHandler {
пробежался по новым классам, кратко описал  их назначение

2024-06-10 18:56 UTC, lazarx77 commented on src/service/InMemoryTaskManager.java
> +            if (tasks.get(id).getStartTime() != null) {
прошелся по всему коду, убрал по максимуму else перевернув блоки if-else, там где это не нарушает логику кода

2024-06-10 18:57 UTC, lazarx77 commented on src/service/InMemoryTaskManager.java
> +                if (prioritizedTasks.contains(task)) {
изменил код

2024-06-11 07:34 UTC, lazarx77 commented on src/adapters/LocalDateTimeAdapter.java
> +//создаем адаптер для gson-json
добавил документирующие комментарии к классам

2024-06-11 15:25 UTC, kriwsha approved these changes

2024-06-11 17:29 UTC, merged